// Auto-generated by LibreLane
module user_project(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  inout vccd1,
  inout vssd1,
  input wb_clk_i,
  input wb_rst_i,
  input wbs_cyc_i,
  input wbs_stb_i,
  input wbs_we_i,
  input[3:0] wbs_sel_i,
  input[31:0] wbs_adr_i,
  input[31:0] wbs_dat_i,
  output wbs_ack_o,
  output[31:0] wbs_dat_o,
  output[2:0] user_irq,
  input uart_rx,
  output uart_tx,
  output pwm_out
);
endmodule
