/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module user_project(pwm_out, uart_rx, uart_tx, wb_clk_i, wb_rst_i, wbs_ack_o, wbs_cyc_i, wbs_stb_i, wbs_we_i, VPWR, VGND, user_irq, wbs_adr_i, wbs_dat_i, wbs_dat_o, wbs_sel_i);
  inout VGND;
  wire VGND;
  inout VPWR;
  wire VPWR;
  output pwm_out;
  wire pwm_out;
  input uart_rx;
  wire uart_rx;
  output uart_tx;
  wire uart_tx;
  output [2:0] user_irq;
  wire [2:0] user_irq;
  input wb_clk_i;
  wire wb_clk_i;
  input wb_rst_i;
  wire wb_rst_i;
  output wbs_ack_o;
  wire wbs_ack_o;
  input [31:0] wbs_adr_i;
  wire [31:0] wbs_adr_i;
  input wbs_cyc_i;
  wire wbs_cyc_i;
  input [31:0] wbs_dat_i;
  wire [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  wire [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  wire [3:0] wbs_sel_i;
  input wbs_stb_i;
  wire wbs_stb_i;
  input wbs_we_i;
  wire wbs_we_i;
endmodule
